/*
 * Created on 2025-07-29 ( 09:46:08 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Accounts"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="Accounts", schema="dbo", catalog="PCBuilder" )
public class Accounts implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="AccountID", nullable=false)
    private Integer    accountid;

    //--- OTHER DATA FIELDS 
    @Column(name="FirstName", length=256)
    private String           firstname    ;

    @Column(name="LastName", length=256)
    private String           lastname    ;

    @Column(name="Email", nullable=false, length=256)
    private String           email    ;

    @Column(name="PasswordHased", length=256)
    private String           passwordhased    ;

    @Column(name="isVerified")
    private Boolean          isverified    ;

    @Column(name="token", length=128)
    private String           token    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tokenExpiry")
    private Date             tokenexpiry    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="accounts")
    private List<Pcs>  listOfPcs;

}