/*
 * Created on 2025-07-24 ( 09:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import jakarta.persistence.*;

/**
 * JPA entity class for "Cases"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="Cases", schema="dbo", catalog="PCBuilder" )
public class Cases implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="type", length=50)
    private String           type    ;

    @Column(name="color", length=50)
    private String           color    ;

    @Column(name="psu")
    private Integer          psu    ;

    @Column(name="side_panel", length=100)
    private String           sidePanel    ;

    @Column(name="external_volume")
    private BigDecimal       externalVolume    ;

    @Column(name="internal_35_bays")
    private Integer          internal35Bays    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;

}