/*
 * Created on 2025-07-24 ( 09:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "Caseaccessory"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="CaseAccessory", schema="dbo", catalog="PCBuilder" )
public class Caseaccessory implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="type", length=50)
    private String           type    ;

    @Column(name="form_factor", length=50)
    private String           formFactor    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;

}