/*
 * Created on 2025-07-24 ( 09:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Components"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="Components", schema="dbo", catalog="PCBuilder" )
public class Components implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ComponentID", nullable=false)
    private Integer    componentid;

    //--- OTHER DATA FIELDS 
    @Column(name="ComponentName", nullable=false, length=100)
    private String           componentname    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="components")
    private List<Pcbuild> listOfPcbuild;

    @OneToMany(mappedBy="components")
    private List<Parts> listOfParts;

}