/*
 * Created on 2025-07-28 ( 02:53:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import jakarta.persistence.*;

/**
 * JPA entity class for "Cpu"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="CPU", schema="dbo", catalog="PCBuilder" )
public class Cpu implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="core_count")
    private Integer          coreCount    ;

    @Column(name="core_clock")
    private BigDecimal       coreClock    ;

    @Column(name="boost_clock")
    private BigDecimal       boostClock    ;

    @Column(name="microarchitecture", length=100)
    private String           microarchitecture    ;

    @Column(name="tdp")
    private Integer          tdp    ;

    @Column(name="graphics", length=100)
    private String           graphics    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;


}