/*
 * Created on 2025-07-28 ( 02:53:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "Cpucooler"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="CPUCooler", schema="dbo", catalog="PCBuilder" )
public class Cpucooler implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="rpm", length=50)
    private String           rpm    ;

    @Column(name="noise_level", length=50)
    private String           noiseLevel    ;

    @Column(name="color", length=50)
    private String           color    ;

    @Column(name="size")
    private Integer          size    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;


}