/*
 * Created on 2025-07-24 ( 09:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import jakarta.persistence.*;

/**
 * JPA entity class for "Externalharddrive"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="ExternalHardDrive", schema="dbo", catalog="PCBuilder" )
public class Externalharddrive implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="type", length=50)
    private String           type    ;

    @Column(name="interface", length=50)
    private String           iface    ;

    @Column(name="capacity")
    private Integer          capacity    ;

    @Column(name="price_per_gb")
    private BigDecimal       pricePerGb    ;

    @Column(name="color", length=50)
    private String           color    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;

}