/*
 * Created on 2025-07-29 ( 09:46:08 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import jakarta.persistence.*;

/**
 * JPA entity class for "Fancontroller"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="FanController", schema="dbo", catalog="PCBuilder" )
public class Fancontroller implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="channels")
    private Integer          channels    ;

    @Column(name="channel_wattage")
    private BigDecimal       channelWattage    ;

    @Column(name="pwm")
    private Boolean          pwm    ;

    @Column(name="form_factor", length=50)
    private String           formFactor    ;

    @Column(name="color", length=50)
    private String           color    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;

}