/*
 * Created on 2025-07-24 ( 09:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "Headphones"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="Headphones", schema="dbo", catalog="PCBuilder" )
public class Headphones implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="type", length=50)
    private String           type    ;

    @Column(name="frequency_response", length=50)
    private String           frequencyResponse    ;

    @Column(name="microphone")
    private Boolean          microphone    ;

    @Column(name="wireless")
    private Boolean          wireless    ;

    @Column(name="enclosure_type", length=50)
    private String           enclosureType    ;

    @Column(name="color", length=50)
    private String           color    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;

}