/*
 * Created on 2025-07-24 ( 09:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "Keyboard"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="Keyboard", schema="dbo", catalog="PCBuilder" )
public class Keyboard implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="style", length=50)
    private String           style    ;

    @Column(name="switches", length=50)
    private String           switches    ;

    @Column(name="backlit", length=50)
    private String           backlit    ;

    @Column(name="tenkeyless")
    private Boolean          tenkeyless    ;

    @Column(name="connection_type", length=50)
    private String           connectionType    ;

    @Column(name="color", length=50)
    private String           color    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;

}