/*
 * Created on 2025-07-29 ( 09:46:08 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import jakarta.persistence.*;

/**
 * JPA entity class for "Memory"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="Memory", schema="dbo", catalog="PCBuilder" )
public class Memory implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="speed", length=50)
    private String           speed    ;

    @Column(name="modules", length=50)
    private String           modules    ;

    @Column(name="price_per_gb")
    private BigDecimal       pricePerGb    ;

    @Column(name="color", length=50)
    private String           color    ;

    @Column(name="first_word_latency")
    private BigDecimal       firstWordLatency    ;

    @Column(name="cas_latency")
    private BigDecimal       casLatency    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;

}