/*
 * Created on 2025-07-28 ( 02:53:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import jakarta.persistence.*;

/**
 * JPA entity class for "Monitor"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="Monitor", schema="dbo", catalog="PCBuilder" )
public class Monitor implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="screen_size")
    private BigDecimal       screenSize    ;

    @Column(name="resolution", length=20)
    private String           resolution    ;

    @Column(name="refresh_rate")
    private Integer          refreshRate    ;

    @Column(name="response_time")
    private BigDecimal       responseTime    ;

    @Column(name="panel_type", length=50)
    private String           panelType    ;

    @Column(name="aspect_ratio", length=10)
    private String           aspectRatio    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;

}