/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "Mouse"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="Mouse", schema="dbo", catalog="PCBuilder" )
public class Mouse implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="tracking_method", length=50)
    private String           trackingMethod    ;

    @Column(name="connection_type", length=50)
    private String           connectionType    ;

    @Column(name="max_dpi")
    private Integer          maxDpi    ;

    @Column(name="hand_orientation", length=10)
    private String           handOrientation    ;

    @Column(name="color", length=50)
    private String           color    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;

}