/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "Opticaldrive"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="OpticalDrive", schema="dbo", catalog="PCBuilder" )
public class Opticaldrive implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="bd", length=50)
    private String           bd    ;

    @Column(name="dvd", length=50)
    private String           dvd    ;

    @Column(name="cd", length=50)
    private String           cd    ;

    @Column(name="bd_write", length=50)
    private String           bdWrite    ;

    @Column(name="dvd_write", length=50)
    private String           dvdWrite    ;

    @Column(name="cd_write", length=50)
    private String           cdWrite    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;

}