
/*
 * Created on 2025-07-25 ( 21:05:27 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * Composite primary key for entity "Pcbuild" ( stored in table "PCBuild" )
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class PcbuildId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Integer    pcid;
    private Integer    componentid;

}
