/*
 * Created on 2025-07-25 ( 21:05:27 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Pcs"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="PCs", schema="dbo", catalog="PCBuilder" )
public class Pcs implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="PCID", nullable=false)
    private Integer    pcid;

    //--- OTHER DATA FIELDS 
    @Column(name="PCName", nullable=false, length=256)
    private String           pcname    ;

    @Column(name="AccountID", nullable=false)
    private Integer          accountid    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="pcs")
    private List<Pcbuild> listOfPcbuild;

    @ManyToOne
    @JoinColumn(name="AccountID", referencedColumnName="AccountID", insertable=false, updatable=false)
    private Accounts   accounts;

}