/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "Powersupply"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="PowerSupply", schema="dbo", catalog="PCBuilder" )
public class Powersupply implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="type", length=50)
    private String           type    ;

    @Column(name="efficiency", length=50)
    private String           efficiency    ;

    @Column(name="wattage")
    private Integer          wattage    ;

    @Column(name="modular", length=50)
    private String           modular    ;

    @Column(name="color", length=50)
    private String           color    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;

}