/*
 * Created on 2025-07-28 ( 02:53:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import jakarta.persistence.*;

/**
 * JPA entity class for "Soundcard"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="SoundCard", schema="dbo", catalog="PCBuilder" )
public class Soundcard implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="channels", length=10)
    private String           channels    ;

    @Column(name="digital_audio")
    private Integer          digitalAudio    ;

    @Column(name="snr")
    private Integer          snr    ;

    @Column(name="sample_rate")
    private BigDecimal       sampleRate    ;

    @Column(name="chipset", length=50)
    private String           chipset    ;

    @Column(name="interface", length=50)
    private String           iface    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;


}