/*
 * Created on 2025-07-24 ( 09:16:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */

package com.project.PCBuilder.persistence.entities;
import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.*;

/**
 * JPA entity class for "Wirelessnetworkcard"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
@Entity
@Table(name="WirelessNetworkCard", schema="dbo", catalog="PCBuilder" )
public class Wirelessnetworkcard implements Serializable {

    private static final long serialVersionUID = 1L;

    
    //--- PRIMARY KEY 
    @Id
    @Column(name="PartID", nullable=false)
    private Integer    partid;

    //--- OTHER DATA FIELDS 
    @Column(name="protocol", length=50)
    private String           protocol    ;

    @Column(name="interface", length=50)
    private String           iface    ;

    @Column(name="color", length=50)
    private String           color    ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
@MapsId
@JoinColumn(name = "PartID")
private Parts parts;

}