/*
 * Created on 2025-07-29 ( 09:46:08 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.persistence.repositories;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;

import com.project.PCBuilder.persistence.entities.Accounts;

/**
 * Spring Data JPA repository for entity "Accounts" <br>
 *
 * This repository extends JpaRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 *   findById, findAll, save, delete, etc <br>
 * with pagination and sorting : <br>
 *   findAll(Pageable), findAll(Sort)<br>
 *
 * This repository can be extended by adding specific "finder" methods.<br>
 * For custom queries, follow Spring Data JPA derived query method conventions.
 *
 * @author Telosys
 */
public interface AccountsRepository extends JpaRepository<Accounts, Integer> {
	Optional<Accounts> findByEmail(String email);
	Optional<Accounts> findByToken(String token);

    // -- Add your custom finder methods below --

    // Example: Find by a String field
    // List<Accounts> findByXxx(String xxx);

    // Example: Find by a field with LIKE behavior
    // List<Accounts> findByXxxContaining(String xxx);

    // Example: Find by a numerical field
    // List<Accounts> findByYyy(BigDecimal yyy);

    // Example: Find by foreign key (like PartID)
    // List<Accounts> findByPartID(Integer partID); // Use Optional<> or single result for OneToOne

}
