/*
 * Created on 2025-07-29 ( 09:46:08 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * DTO class for "Accounts"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class AccountsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer accountid;

    //--- OTHER DATA FIELDS 
    private String   firstname;
    private String   lastname;
    private String   email;
    private String   passwordhased;
    private Boolean   isverified;
    private String   token;
    private Date   tokenexpiry;

    //--- LINKS ( RELATIONSHIPS )
        @JsonBackReference
        private List<PcsDTO> listOfPcs;

}
