/*
 * Created on 2025-07-26 ( 23:17:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * DTO class for "Cases"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class CasesDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer partid;

    //--- OTHER DATA FIELDS 
    private String   type;
    private String   color;
    private Integer   psu;
    private String   sidePanel;
    private BigDecimal   externalVolume;
    private Integer   internal35Bays;

    //--- LINKS ( RELATIONSHIPS )
        
        private PartsDTO parts;

}
