/*
 * Created on 2025-07-26 ( 23:17:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * DTO class for "Casefan"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class CasefanDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer partid;

    //--- OTHER DATA FIELDS 
    private Integer   size;
    private String   color;
    private String   rpm;
    private String   airflow;
    private String   noiseLevel;
    private Boolean   pwm;

    //--- LINKS ( RELATIONSHIPS )
        
        private PartsDTO parts;

}
