/*
 * Created on 2025-07-26 ( 23:17:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import io.swagger.v3.oas.annotations.media.Schema;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * DTO class for "Components"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class ComponentsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    private Integer componentid;

    //--- OTHER DATA FIELDS 
    private String   componentname;

    //--- LINKS ( RELATIONSHIPS )
        @JsonIgnore
        private List<PcbuildDTO> listOfPcbuild;
        @JsonIgnore
        private List<PartsDTO> listOfParts;

}
