/*
 * Created on 2025-07-28 ( 02:53:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * DTO class for "Cpucooler"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class CpucoolerDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer partid;

    //--- OTHER DATA FIELDS 
    private String   rpm;
    private String   noiseLevel;
    private String   color;
    private Integer   size;

    //--- LINKS ( RELATIONSHIPS )
        
        private PartsDTO parts;

}
