/*
 * Created on 2025-07-29 ( 09:46:08 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * DTO class for "Internalharddrive"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class InternalharddriveDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer partid;

    //--- OTHER DATA FIELDS 
    private BigDecimal   capacity;
    private BigDecimal   pricePerGb;
    private String   type;
    private Integer   cache;
    private String   formFactor;
    private String   iface;

    //--- LINKS ( RELATIONSHIPS )
        @JsonManagedReference
        private PartsDTO parts;

}
