/*
 * Created on 2025-07-26 ( 23:17:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * DTO class for "Pcs"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class PcsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer pcid;

    //--- OTHER DATA FIELDS 
    private String   pcname;
    private Integer   accountid;

    //--- LINKS ( RELATIONSHIPS )
        @JsonIgnore
        private List<PcbuildDTO> listOfPcbuild;
        
        private AccountsDTO accounts;

}
