/*
 * Created on 2025-07-28 ( 02:53:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * DTO class for "Speakers"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class SpeakersDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer partid;

    //--- OTHER DATA FIELDS 
    private String   configuration;
    private BigDecimal   wattage;
    private String   frequencyResponse;
    private String   color;

    //--- LINKS ( RELATIONSHIPS )
       
        private PartsDTO parts;

}
