/*
 * Created on 2025-07-26 ( 23:17:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.dto;

import java.io.Serializable;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * DTO class for "Units"
 *
 * @author Telosys
 */
@Data
@NoArgsConstructor
public class UnitsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer unitid;

    //--- OTHER DATA FIELDS 
    private String   tablename;
    private String   fieldname;
    private String   unitcode;


}
