/*
 * Created on 2025-07-27 ( 01:57:20 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.services;

import java.util.List;
import java.util.Optional;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.project.PCBuilder.persistence.entities.Components;
import com.project.PCBuilder.persistence.repositories.ComponentsRepository;
import com.project.PCBuilder.rest.dto.ComponentsDTO;
import com.project.PCBuilder.rest.services.commons.GenericService;


/**
 * REST service for entity "Components" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * Enhanced to handle foreign key relationships and one-to-one cascading <br>
 * 
 * @author Telosys
 *
 */
@Service
@Transactional
public class ComponentsService extends GenericService<Components, ComponentsDTO> {

	private static final Logger logger = LoggerFactory.getLogger(ComponentsService.class);

	private final ComponentsRepository repository; // injected by constructor


	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 */
	public ComponentsService(ComponentsRepository repository) {
		super(Components.class, ComponentsDTO.class);
		this.repository = repository;
	}
	
	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private Integer getEntityId(ComponentsDTO dto) {
		return dto.getComponentid();
	}

	/**
	 * Validates foreign key references before saving
	 *
	 * @param dto
	 * @throws IllegalArgumentException if any FK reference is invalid
	 */
	private void validateForeignKeyReferences(ComponentsDTO dto) {
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<ComponentsDTO> findAll() {
		logger.debug("findAll()");
		Iterable<Components> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param componentid 
	 * @return the entity or null if not found
	 */
	public ComponentsDTO findById(Integer componentid) {
		Integer entityId = componentid;
		logger.debug("findById({})", entityId);
		Optional<Components> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist) <br>
	 * Validates foreign key references before saving
	 *
	 * @param componentid 
	 * @param dto 
	 */
	public void save(Integer componentid, ComponentsDTO dto) {
		Integer entityId = componentid;
		logger.debug("save({},{})", entityId, dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		// force PK in DTO (just to be sure to conform with the given PK) 
		dto.setComponentid(componentid);


		repository.save(dtoToEntity(dto));
	}

	/**
	 * Updates the given entity if it exists <br>
	 * Validates foreign key references before updating
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(ComponentsDTO dto) {
		logger.debug("update({})", dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // found and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists <br>
	 * Validates foreign key references for non-null FK fields
	 *
	 * @param componentid 
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(Integer componentid, ComponentsDTO dto) {
		Integer entityId = componentid;
		logger.debug("partialUpdate({}, {})", entityId, dto);
		
		Optional<Components> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			Components entity = optionalEntity.get();
			
			// Update only non-null fields from DTO
			if (dto.getComponentname() != null) {
				entity.setComponentname(dto.getComponentname());
			}
			
			repository.save(entity);
			return true; // found and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity <br>
	 * Validates foreign key references before creating
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(ComponentsDTO dto) {
		logger.debug("create({})", dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		// auto-generated Primary Key
		repository.save(dtoToEntity(dto));
		return true; // always created
	}


	/**
	 * Deletes an entity by its PK <br>
	 * Handles cascading delete for one-to-one relationships
	 *
	 * @param componentid 
	 * @return true if deleted, false if not found
	 */
	
	public boolean deleteById(Integer componentid) {
		Integer entityId = componentid;
		logger.debug("deleteById({})", entityId);
		
		if (repository.existsById(entityId)) {
			
			repository.deleteById(entityId);
			return true; // found and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders" for foreign key relationships
	// -----------------------------------------------------------------------------------------


/***
	// Example custom finders - uncomment and modify as needed
	public List<ComponentsDTO> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		List<Components> list = repository.findByTitleContaining(title);
		return entityListToDtoList(list);
	}

	public List<ComponentsDTO> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		List<Components> list = repository.findByPrice(price);
		return entityListToDtoList(list);
	}
***/
}