/*
 * Created on 2025-07-27 ( 01:57:20 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.services;

import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.project.PCBuilder.persistence.entities.Parts;
import com.project.PCBuilder.persistence.repositories.PartsRepository;
import com.project.PCBuilder.rest.dto.PartsDTO;
import com.project.PCBuilder.rest.services.commons.GenericService;

import com.project.PCBuilder.persistence.entities.Components;
import com.project.PCBuilder.persistence.repositories.ComponentsRepository;

/**
 * REST service for entity "Parts" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * Enhanced to handle foreign key relationships and one-to-one cascading <br>
 * 
 * @author Telosys
 *
 */
@Service
@Transactional
public class PartsService extends GenericService<Parts, PartsDTO> {

	private static final Logger logger = LoggerFactory.getLogger(PartsService.class);

	private final PartsRepository repository; // injected by constructor

	private final ComponentsRepository componentsRepository;

	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 * @param componentsRepository the Components repository to be injected
	 */
	public PartsService(PartsRepository repository, ComponentsRepository componentsRepository) {
		super(Parts.class, PartsDTO.class);
		this.repository = repository;
		this.componentsRepository = componentsRepository;
	}
	
	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private Integer getEntityId(PartsDTO dto) {
		return dto.getPartid();
	}

	/**
	 * Validates foreign key references before saving
	 *
	 * @param dto
	 * @throws IllegalArgumentException if any FK reference is invalid
	 */
	private void validateForeignKeyReferences(PartsDTO dto) {
		// Validate Components reference
		if (dto.getComponentid() != null) {
			if (!componentsRepository.existsById(dto.getComponentid())) {
				throw new IllegalArgumentException("Invalid Components reference: " + dto.getComponentid());
			}
		}
	}

	/**
	 * Sets the Components entity in the Parts entity based on componentid from DTO
	 *
	 * @param entity the Parts entity
	 * @param dto the PartsDTO containing componentid
	 */
	private void setComponentsEntity(Parts entity, PartsDTO dto) {
		if (dto.getComponentid() != null) {
			Optional<Components> componentsOptional = componentsRepository.findById(dto.getComponentid());
			if (componentsOptional.isPresent()) {
				entity.setComponents(componentsOptional.get());
			} else {
				throw new IllegalArgumentException("Components with ID " + dto.getComponentid() + " not found");
			}
		}
	}

	/**
	 * Enhanced DTO to Entity conversion that handles Components relationship
	 *
	 * @param dto
	 * @return
	 */
	@Override
	protected Parts dtoToEntity(PartsDTO dto) {
		Parts entity = super.dtoToEntity(dto);
		// Set the Components entity based on componentid
		setComponentsEntity(entity, dto);
		return entity;
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<PartsDTO> findAll() {
		logger.debug("findAll()");
		Iterable<Parts> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param partid 
	 * @return the entity or null if not found
	 */
	public PartsDTO findById(Integer partid) {
		Integer entityId = partid;
		logger.debug("findById({})", entityId);
		Optional<Parts> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist) <br>
	 * Validates foreign key references before saving
	 *
	 * @param partid 
	 * @param dto 
	 */
	public void save(Integer partid, PartsDTO dto) {
		Integer entityId = partid;
		logger.debug("save({},{})", entityId, dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		// force PK in DTO (just to be sure to conform with the given PK) 
		dto.setPartid(partid);

		repository.save(dtoToEntity(dto));
	}

	/**
	 * Updates the given entity if it exists <br>
	 * Validates foreign key references before updating
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(PartsDTO dto) {
		logger.debug("update({})", dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // found and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists <br>
	 * Validates foreign key references for non-null FK fields
	 *
	 * @param partid 
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(Integer partid, PartsDTO dto) {
		Integer entityId = partid;
		logger.debug("partialUpdate({}, {})", entityId, dto);
		
		Optional<Parts> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			Parts entity = optionalEntity.get();
			
			// Update only non-null fields from DTO
			if (dto.getPartname() != null) {
				entity.setPartname(dto.getPartname());
			}
			if (dto.getPartprice() != null) {
				entity.setPartprice(dto.getPartprice());
			}
			if (dto.getComponentid() != null) {
				// Validate FK reference before updating
				if (!componentsRepository.existsById(dto.getComponentid())) {
					throw new IllegalArgumentException("Invalid Components reference: " + dto.getComponentid());
				}
				// Set the Components entity instead of componentid
				Optional<Components> componentsOptional = componentsRepository.findById(dto.getComponentid());
				if (componentsOptional.isPresent()) {
					entity.setComponents(componentsOptional.get());
				}
			}
			
			repository.save(entity);
			return true; // found and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity <br>
	 * Validates foreign key references before creating
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(PartsDTO dto) {
		logger.debug("create({})", dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		// auto-generated Primary Key
		repository.save(dtoToEntity(dto));
		return true; // always created
	}

	/**
	 * Deletes an entity by its PK <br>
	 * Handles cascading delete for one-to-one relationships
	 *
	 * @param partid 
	 * @return true if deleted, false if not found
	 */
	public boolean deleteById(Integer partid) {
		Integer entityId = partid;
		logger.debug("deleteById({})", entityId);
		
		if (repository.existsById(entityId)) {
			
			repository.deleteById(entityId);
			return true; // found and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders" for foreign key relationships
	// -----------------------------------------------------------------------------------------
	
	/**
	 * Finds entities by Components reference
	 *
	 * @param componentid the Components ID
	 * @return list of entities
	 */
	/***
	public List<PartsDTO> findByComponents(Integer componentid) {
		logger.debug("findByComponents({})", componentid);
		List<Parts> list = repository.findByComponentID(componentid);
		return entityListToDtoList(list);
	}

/***
	// Example custom finders - uncomment and modify as needed
	public List<PartsDTO> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		List<Parts> list = repository.findByTitleContaining(title);
		return entityListToDtoList(list);
	}

	public List<PartsDTO> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		List<Parts> list = repository.findByPrice(price);
		return entityListToDtoList(list);
	}
***/
}