/*
 * Created on 2025-07-27 ( 01:57:20 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.services;

import java.util.List;
import java.util.Optional;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.project.PCBuilder.persistence.entities.Pcs;
import com.project.PCBuilder.persistence.repositories.PcsRepository;
import com.project.PCBuilder.rest.dto.PcsDTO;
import com.project.PCBuilder.rest.services.commons.GenericService;

import com.project.PCBuilder.persistence.entities.Accounts;
import com.project.PCBuilder.persistence.repositories.AccountsRepository;

/**
 * REST service for entity "Pcs" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * Enhanced to handle foreign key relationships and one-to-one cascading <br>
 * 
 * @author Telosys
 *
 */
@Service
@Transactional
public class PcsService extends GenericService<Pcs, PcsDTO> {

	private static final Logger logger = LoggerFactory.getLogger(PcsService.class);

	private final PcsRepository repository; // injected by constructor

	private final AccountsRepository accountsRepository;

	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 * @param accountsRepository the Accounts repository to be injected
	 */
	public PcsService(PcsRepository repository, AccountsRepository accountsRepository) {
		super(Pcs.class, PcsDTO.class);
		this.repository = repository;
		this.accountsRepository = accountsRepository;
	}
	
	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private Integer getEntityId(PcsDTO dto) {
		return dto.getPcid();
	}

	/**
	 * Validates foreign key references before saving
	 *
	 * @param dto
	 * @throws IllegalArgumentException if any FK reference is invalid
	 */
	private void validateForeignKeyReferences(PcsDTO dto) {
		// Validate Accounts reference
		if (dto.getAccountid() != null) {
			if (!accountsRepository.existsById(dto.getAccountid())) {
				throw new IllegalArgumentException("Invalid Accounts reference: " + dto.getAccountid());
			}
		}
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<PcsDTO> findAll() {
		logger.debug("findAll()");
		Iterable<Pcs> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param pcid 
	 * @return the entity or null if not found
	 */
	public PcsDTO findById(Integer pcid) {
		Integer entityId = pcid;
		logger.debug("findById({})", entityId);
		Optional<Pcs> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist) <br>
	 * Validates foreign key references before saving
	 *
	 * @param pcid 
	 * @param dto 
	 */
	public void save(Integer pcid, PcsDTO dto) {
		Integer entityId = pcid;
		logger.debug("save({},{})", entityId, dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		// force PK in DTO (just to be sure to conform with the given PK) 
		dto.setPcid(pcid);


		repository.save(dtoToEntity(dto));
	}

	/**
	 * Updates the given entity if it exists <br>
	 * Validates foreign key references before updating
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(PcsDTO dto) {
		logger.debug("update({})", dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // found and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists <br>
	 * Validates foreign key references for non-null FK fields
	 *
	 * @param pcid 
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(Integer pcid, PcsDTO dto) {
		Integer entityId = pcid;
		logger.debug("partialUpdate({}, {})", entityId, dto);
		
		Optional<Pcs> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			Pcs entity = optionalEntity.get();
			
			// Update only non-null fields from DTO
			if (dto.getPcname() != null) {
				entity.setPcname(dto.getPcname());
			}
			if (dto.getAccountid() != null) {
				// Validate FK reference before updating
				if (!accountsRepository.existsById(dto.getAccountid())) {
					throw new IllegalArgumentException("Invalid Accounts reference: " + dto.getAccountid());
				}
				entity.setAccountid(dto.getAccountid());
			}
			
			repository.save(entity);
			return true; // found and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity <br>
	 * Validates foreign key references before creating
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(PcsDTO dto) {
		logger.debug("create({})", dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		// auto-generated Primary Key
		repository.save(dtoToEntity(dto));
		return true; // always created
	}


	/**
	 * Deletes an entity by its PK <br>
	 * Handles cascading delete for one-to-one relationships
	 *
	 * @param pcid 
	 * @return true if deleted, false if not found
	 */
	public boolean deleteById(Integer pcid) {
		Integer entityId = pcid;
		logger.debug("deleteById({})", entityId);
		
		if (repository.existsById(entityId)) {
			
			repository.deleteById(entityId);
			return true; // found and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders" for foreign key relationships
	// -----------------------------------------------------------------------------------------
	
	/**
	 * Finds entities by Accounts reference
	 *
	 * @param accountid the Accounts ID
	 * @return list of entities
	 */
	/***
	public List<PcsDTO> findByAccounts(Integer accountid) {
		logger.debug("findByAccounts({})", accountid);
		List<Pcs> list = repository.findByAccountID(accountid);
		return entityListToDtoList(list);
	}


/***
	// Example custom finders - uncomment and modify as needed
	public List<PcsDTO> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		List<Pcs> list = repository.findByTitleContaining(title);
		return entityListToDtoList(list);
	}

	public List<PcsDTO> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		List<Pcs> list = repository.findByPrice(price);
		return entityListToDtoList(list);
	}
***/
}