/*
 * Created on 2025-07-27 ( 01:57:20 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.services;

import java.util.List;
import java.util.Optional;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.project.PCBuilder.persistence.entities.Units;
import com.project.PCBuilder.persistence.repositories.UnitsRepository;
import com.project.PCBuilder.rest.dto.UnitsDTO;
import com.project.PCBuilder.rest.services.commons.GenericService;


/**
 * REST service for entity "Units" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * Enhanced to handle foreign key relationships and one-to-one cascading <br>
 * 
 * @author Telosys
 *
 */
@Service
@Transactional
public class UnitsService extends GenericService<Units, UnitsDTO> {

	private static final Logger logger = LoggerFactory.getLogger(UnitsService.class);

	private final UnitsRepository repository; // injected by constructor


	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 */
	public UnitsService(UnitsRepository repository) {
		super(Units.class, UnitsDTO.class);
		this.repository = repository;
	}
	
	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private Integer getEntityId(UnitsDTO dto) {
		return dto.getUnitid();
	}

	/**
	 * Validates foreign key references before saving
	 *
	 * @param dto
	 * @throws IllegalArgumentException if any FK reference is invalid
	 */
	private void validateForeignKeyReferences(UnitsDTO dto) {
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<UnitsDTO> findAll() {
		logger.debug("findAll()");
		Iterable<Units> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param unitid 
	 * @return the entity or null if not found
	 */
	public UnitsDTO findById(Integer unitid) {
		Integer entityId = unitid;
		logger.debug("findById({})", entityId);
		Optional<Units> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist) <br>
	 * Validates foreign key references before saving
	 *
	 * @param unitid 
	 * @param dto 
	 */
	public void save(Integer unitid, UnitsDTO dto) {
		Integer entityId = unitid;
		logger.debug("save({},{})", entityId, dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		// force PK in DTO (just to be sure to conform with the given PK) 
		dto.setUnitid(unitid);


		repository.save(dtoToEntity(dto));
	}

	/**
	 * Updates the given entity if it exists <br>
	 * Validates foreign key references before updating
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(UnitsDTO dto) {
		logger.debug("update({})", dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // found and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists <br>
	 * Validates foreign key references for non-null FK fields
	 *
	 * @param unitid 
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(Integer unitid, UnitsDTO dto) {
		Integer entityId = unitid;
		logger.debug("partialUpdate({}, {})", entityId, dto);
		
		Optional<Units> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			Units entity = optionalEntity.get();
			
			// Update only non-null fields from DTO
			if (dto.getTablename() != null) {
				entity.setTablename(dto.getTablename());
			}
			if (dto.getFieldname() != null) {
				entity.setFieldname(dto.getFieldname());
			}
			if (dto.getUnitcode() != null) {
				entity.setUnitcode(dto.getUnitcode());
			}
			
			repository.save(entity);
			return true; // found and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity <br>
	 * Validates foreign key references before creating
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(UnitsDTO dto) {
		logger.debug("create({})", dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		// auto-generated Primary Key
		repository.save(dtoToEntity(dto));
		return true; // always created
	}


	/**
	 * Deletes an entity by its PK <br>
	 * Handles cascading delete for one-to-one relationships
	 *
	 * @param unitid 
	 * @return true if deleted, false if not found
	 */
	public boolean deleteById(Integer unitid) {
		Integer entityId = unitid;
		logger.debug("deleteById({})", entityId);
		
		if (repository.existsById(entityId)) {
			
			repository.deleteById(entityId);
			return true; // found and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders" for foreign key relationships
	// -----------------------------------------------------------------------------------------

	/**
	 * Finds units by table name and field name
	 *
	 * @param tableName
	 * @param fieldName
	 * @return list of matching units
	 */
	
	/***
	public List<UnitsDTO> findByTableNameAndFieldName(String tableName, String fieldName) {
		logger.debug("findByTableNameAndFieldName({}, {})", tableName, fieldName);
		List<Units> list = repository.findByTableNameAndFieldName(tableName, fieldName);
		return entityListToDtoList(list);
	}
	
	/**
	 * Finds units by table name
	 *
	 * @param tableName
	 * @return list of matching units
	 */
	/***
	public List<UnitsDTO> findByTableName(String tableName) {
		logger.debug("findByTableName({})", tableName);
		List<Units> list = repository.findByTableName(tableName);
		return entityListToDtoList(list);
	}


	// Example custom finders - uncomment and modify as needed
	public List<UnitsDTO> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		List<Units> list = repository.findByTitleContaining(title);
		return entityListToDtoList(list);
	}

	public List<UnitsDTO> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		List<Units> list = repository.findByPrice(price);
		return entityListToDtoList(list);
	}
***/
}